AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Server for the Visory events challenge project

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  DiscoveryApiKey:
    Type: String
    Description: Ticketmaster Discovery API Key.
  FrontendUrl:
    Type: String
    Description: Url of the frontend application. This is used to allow CORS requests from the frontend.
    Default: http://localhost:4200

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getEventsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Returns all events from TicketMaster API
      Environment:
        Variables:
          API_KEY: !Ref DiscoveryApiKey
          FRONTEND_URL: !Ref FrontendUrl
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RequestParameters:
              - method.request.querystring.countryCode:
                  Required: false
              - method.request.querystring.postalCode:
                  Required: false
              - method.request.querystring.startDateTime:
                  Required: false
              - method.request.querystring.endDateTime:
                  Required: false
              - method.request.querystring.page:
                  Required: false
              - method.request.querystring.size:
                  Required: false

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
